const ApiRoutes = {
  BaseURL: 'https://web.usmank.site',
  forgotPassword: '/forgot-password',
  newPassword: '/reset-password',
  login: '/login',
  logout: '/logout',
  addEmployee: '/add-user',
  getStaff: '/get-users',
  getAllDepartments: '/department/get-all-departments',
  getAllLocations: '/location/get-all-locations',
  getAllJobRoles: '/jobrole/get-all-jobroles',
  getMeta: '/get-meta',
  getUser: '/user/get-user/{0}',
  updateUser: '/users/{0}',
  deleteUser: '/user/delete-user',
  restoreUser: '/user/restore-user/{0}',
  clockOperation: '/clock',
  addNote: '/add-note',
  clockIn: '/timeentry/clock-in',
  clockOut: '/timeentry/clock-out',
  break: '/break',
  startBreak: '/timeentry/add-break',
  endBreak: '/timeentry/end-break',
  shiftStatus: '/clock/status',
  breakStatus: '/timeentry/get-shift-breaks-status',
  whoIsOn: '/timeentry/whos-on',
};

export default ApiRoutes;
