import { COMMON_CONSTANTS_TYPE } from '../features/types';

const COMMON_CONSTANTS: COMMON_CONSTANTS_TYPE = {
  DEFAULT: '',
  PICKER_VALUES: {
    ADMIN: 'Admin',
    USER: 'User',
  },
  API_HEADERS: {
    CONTENT_TYPE: 'Content-Type',
    APPLICATION_JSON: 'application/json',
    ACCEPT: '*/*',
    BEARER: 'Bearer',
  },
  END: 'end',
  ZERO: 0,
  ONE: 1,
  SPACE: ' ',
  ADMIN: 'Admin',
  REDUX_TYPES: {
    SET_USER: 'SET_USER',
    SET_TOKENS: 'SET_TOKENS',
    LOGIN_USER: 'LOGIN_USER',
    LOGIN_FAIL: 'LOGIN_FAIL',
    LOGOUT: 'LOGOUT',
    SET_UPDATED_STAFF_LIST: 'SET_UPDATED',
    SET_UPDATED_WHO_IS_ON_LIST: 'SET_UPDATED_WHO_IS_ON_LIST',
    SET_REFRESH_FLAG: 'SET_REFRESH_FLAG',
  },
  ICONS: {
    HOME: 'home-outline',
    PEOPLE: 'people-outline',
    ADD: 'add-outline',
    EDIT: 'create-outline',
    SAVE: 'save-outline',
    CREATE: 'create-outline',
    SEARCH: 'search-outline',
    FILTER: 'filter-outline',
    ARROW: 'arrow-back-outline',
    ALARM: 'alarm-outline',
    SETTINGS: 'settings-outline',
    LOG_OUT: 'log-out-outline',
    CLOCK: 'time-outline',
    CLOSE: 'close',
    ELLIPSE: 'ellipse',
    CAFE: 'cafe-outline',
  },
  DATE_TIME: {
    NUMERIC: 'numeric',
    SHORT: 'short',
    TWO_DIGIT: '2-digit',
    EN_US: 'en-US',
  },
  FORM_CONTROLLER_VALUES: {
    FIRST_NAME: 'firstName',
    LAST_NAME: 'lastName',
    EMAIL: 'email',
    PASSWORD: 'password',
    PHONE_NUMBER: 'phoneNumber',
    USERNAME: 'username',
    NICKNAME: 'nickname',
    ADDRESS: 'address',
    USER_CODE: 'userCode',
    DEPARTMENT: 'department',
    LOCATION: 'location',
    JOB_ROLE: 'jobRole',
    ROLE: 'role',
  },
  FLEX: {
    ROW: 'row',
    COLUMN: 'column',
    CENTER: 'center',
    SPACE_BETWEEN: 'space-between',
    FLEX_START: 'flex-start',
    FLEX_END: 'flex-end',
  },
  ALIGN: {
    RIGHT: 'right',
    LEFT: 'left',
    CENTER: 'center',
  },
  POSITION: {
    ABSOLUTE: 'absolute',
    RELATIVE: 'relative',
  },
  SIZE: {
    SIZE_1: 1,
    SIZE_2: 2,
    SIZE_3: 3,
    SIZE_4: 4,
    SIZE_5: 5,
    SIZE_8: 8,
    SIZE_10: 10,
    SIZE_12: 12,
    SIZE_14: 14,
    SIZE_15: 15,
    SIZE_16: 16,
    SIZE_17: 17,
    SIZE_18: 18,
    SIZE_20: 20,
    SIZE_21: 21,
    SIZE_22: 22,
    SIZE_24: 24,
    SIZE_26: 26,
    SIZE_28: 28,
    SIZE_30: 30,
    SIZE_32: 32,
    SIZE_33: 33,
    SIZE_34: 34,
    SIZE_36: 36,
    SIZE_40: 40,
    SIZE_48: 48,
    SIZE_50: 50,
    SIZE_57: 57,
    SIZE_60: 60,
    SIZE_100: 100,
    SIZE_120: 120,
    SIZE_150: 150,
    SIZE_200: 200,
    SIZE_220: 220,
  },
  TIME_CONSTANTS: {
    ZERO: 0,
    ONE: 1,
    DECIMAL: 10,
    MINUTE: 60,
    HOUR: 3600,
    MINUTE_IN_MS: 60000,
  },
};

export default COMMON_CONSTANTS;
