export const colors = {
  CLOCKWISE_PRIMARY: '#00bcd4',
  CLOCKWISE_PRIMARY_DARK: '#008ba3',
  BACKGROUND_DARK_MODE: '#0E2747',
  BACKGROUND_DARKER_MODE: '#0A1B2D',
  BACKGROUND_LIGHT_MODE: '#FFFFF',
  BACKGROUND_LIGHTER_MODE: '#A3BEC0',

  TEXT_DARK_MODE: 'white',
  TEXT_LIGHT_MODE: 'black',
  TEXT_DARK_LIGHTER_MODE: '#656565',
  TEXT_LIGHT_LIGHTER_MODE: '#656565',
};

export const fonts = {
  CLOCKWISE_REGULAR: 'Lato-Regular',
  CLOCKWISE_BOLD: 'Lato-Bold',
};
