export const colors = {
  CLOCKWISE_PRIMARY: '#00bcd4',
  CLOCKWISE_PRIMARY_DARK: '#008ba3',
  BACKGROUND_DARK_MODE: '#0E2747',
  BACKGROUND_DARKER_MODE: '#0A1B2D',
  BACKGROUND_LIGHT_MODE: 'white',
  BACKGROUND_LIGHTER_MODE: '#E6E6E2',
  BACKGROUND_DARK_FORMS: '#012451',
  BACKGROUND_LIGHT_FORMS: '#F0F4F5',
  BACKGROUND_ICONS_LIGHT_MODE: '#cacccc',
  BACKGROUND_ICONS_DARK_MODE: '#1c1c1c',

  BORDER_COLOR_LIGHT_MODE: '#E0E0E0',
  BORDER_COLOR_DARK_MODE: '#2c2c2c',
  TEXT_DARK_MODE: 'white',
  TEXT_LIGHT_MODE: 'black',
  TEXT_DARK_LIGHTER_MODE: '#656565',
  TEXT_LIGHT_LIGHTER_MODE: '#656565',
  RANDOM_COLOR_ARRAY: ['#07CF99', '#086DBF', '#B63C08', '#F0F30D', '#0ED4EA'],
};

export const fonts = {
  CLOCKWISE_REGULAR: 'Lato-Regular',
  CLOCKWISE_BOLD: 'Lato-Bold',
};
